### ISSUE TITLE
Add custom styles to Pug files

### ISSUE THREAD

**Issue by VitorLuizC** [vharadkou/OperatorMonoDarkTheme#1]
Pug properties aren't italic and keep default dark syntax color, instead of that cool yellow color.
Mixins and other pug things keep default theme, but they don't exist on regular HTML, so i don't expect such stuff.

![Screenshot comparing each other](https://cloud.githubusercontent.com/assets/9027363/25760677/4679c93a-31ae-11e7-9758-b931b69550fc.png)

**Comment by vharadkou** [comment]
Thanks, this issue is fixed.
