### ISSUE TITLE
OperatorMonoLightTheme ?

### ISSUE THREAD

**Issue by charliegn** [vharadkou/OperatorMonoDarkTheme#4]
I love this theme.  Any chance you'd be willing to create a OperatorMonoLightTheme as well?  I use the dark most always, but when the sunlight the shines behind my screens is bright, switching over to a light theme which makes it easier on the eyes.  

No biggie either way, I think that you just hit it out of the park with this theme, I love everything about it so I thought I'd ask. 😃

**Comment by vharadkou** [comment]
coming soon...

**Comment by sebastianschnock** [comment]
Hey there, thank you for this great theme! I just wanted to chime in hoping for a light version of this theme 😉
Cheers!

**Comment by ashut0shk** [comment]
@vharadkou You have done a commendable work on the theme styling. I was hoping if you have any plans to add a light color scheme as well. Thanks

**Comment by vharadkou** [comment]
@charliegn @sebastianschnock @ashut0shk

Today I released version 2.0. It contains four themes: Dark, Dark Modern, Light, and Light Modern.

Please feel free to let me know if you have any suggestions.
