### ISSUE TITLE
Update to match default theme

### ISSUE THREAD

**Issue by mvanderlee** [vharadkou/OperatorMonoDarkTheme#5]
The default dark_plus theme has been updated to provide more syntax coloring.

My use-case is the python string formatting `"Hello %(variable)s"`. Using the default theme the `%(variable)s` gets a different color than the rest of the string.  In OperatorMonoDarkTheme it does not.

**Comment by vharadkou** [comment]
will update it today or tomorrow

**Comment by mvanderlee** [comment]
Great, thanks for the great theme!

**Comment by vharadkou** [comment]
done
