### ISSUE TITLE
editor.semanticHighlighting is not supported

### ISSUE THREAD

**Issue by ackvf** [vharadkou/OperatorMonoDarkTheme#8]
`editor.semanticHighlighting.enabled` was added in v1.43.1

left default Dark+

![image](https://user-images.githubusercontent.com/2313018/86354793-f66abe00-bc69-11ea-8221-7b6bb72cd6a8.png)
![image](https://user-images.githubusercontent.com/2313018/86354936-2b771080-bc6a-11ea-8d67-94147d4a6db6.png)

notice mostly the yellow colors for functions even when they are not called, which is super usefull to spot errors
![image](https://user-images.githubusercontent.com/2313018/86355544-1fd81980-bc6b-11ea-80c1-10186eb5f299.png)
![image](https://user-images.githubusercontent.com/2313018/86355562-26ff2780-bc6b-11ea-94ed-dae9c38c175a.png)

**Comment by vharadkou** [comment]
closed with version 1.0.0
